// ─── Visual Plan Types ────────────────────────────────────────────────────────
// Rich, reviewable plan surface for Agile Agent Canvas.  A VisualPlan is a
// first-class canvas artifact generated by the AI provider, rendered in the
// existing DetailPanel, and acts as the approval gate before code/story dispatch.
//
// See .claude/PRPs/plans/visual-plan-integration.plan.md for the full spec.

// ── Section kinds ────────────────────────────────────────────────────────────

export type PlanSectionKind =
  | 'overview'
  | 'fileMap'
  | 'diagram'
  | 'wireframe'
  | 'apiSpec'
  | 'schemaMap'
  | 'annotatedCode'
  | 'openQuestions'
  | 'tasks';

// ── Plan status ──────────────────────────────────────────────────────────────

export type PlanStatus =
  | 'generating'
  | 'pending'
  | 'changes-requested'
  | 'approved'
  | 'dispatched'
  | 'failed';

// ── Section payloads ─────────────────────────────────────────────────────────

export interface PlanComment {
  id: string;
  sectionId: string;
  body: string;
  author?: string;
  createdAt: number;
}

export interface PlanTask {
  id: string;
  title: string;
  description?: string;
  priority?: string;
  scope?: string[];
  selected?: boolean;
}

export interface FileMapEntry {
  path: string;
  change: 'add' | 'modify' | 'delete' | 'rename';
  note?: string;
}

export interface DiagramSpec {
  id: string;
  title?: string;
  mermaid?: string;
  nodes?: { id: string; label: string }[];
  edges?: { from: string; to: string; label?: string }[];
}

export interface WireframeSpec {
  id: string;
  title?: string;
  description?: string;
  sections?: { id: string; label: string; elements?: { type: string; label: string }[] }[];
}

export interface ApiSpecEntry {
  method: string;
  path: string;
  summary?: string;
  requestBody?: string;
  responses?: { code: string; description: string }[];
}

export interface SchemaEntity {
  name: string;
  fields?: { name: string; type: string; required?: boolean }[];
  relationships?: { target: string; type: string; cardinality?: string }[];
}

export interface AnnotatedCodeBlock {
  file: string;
  language?: string;
  code: string;
  annotations?: { line: number; comment: string }[];
}

export interface OpenQuestion {
  id: string;
  question: string;
  status?: 'open' | 'answered' | 'blocked';
  answer?: string;
}

// ── Discriminated section union ──────────────────────────────────────────────

export type PlanSection =
  | { id: string; kind: 'overview'; markdown: string; risk?: 'low' | 'medium' | 'high'; groundedFiles?: string[] }
  | { id: string; kind: 'fileMap'; entries: FileMapEntry[] }
  | { id: string; kind: 'diagram'; diagram: DiagramSpec }
  | { id: string; kind: 'wireframe'; wireframe: WireframeSpec }
  | { id: string; kind: 'apiSpec'; entries: ApiSpecEntry[] }
  | { id: string; kind: 'schemaMap'; entities: SchemaEntity[] }
  | { id: string; kind: 'annotatedCode'; blocks: AnnotatedCodeBlock[] }
  | { id: string; kind: 'openQuestions'; questions: OpenQuestion[] }
  | { id: string; kind: 'tasks'; tasks: PlanTask[] };

// ── VisualPlan ───────────────────────────────────────────────────────────────

export interface VisualPlan {
  id: string;
  title: string;
  goal: string;
  status: PlanStatus;
  createdAt: number;
  updatedAt: number;
  /** When generated from a specific story/epic artifact. */
  sourceArtifactId?: string;
  /** Artifact ids this plan affects → draws canvas dependency arrows. */
  targets?: string[];
  sections: PlanSection[];
  comments: PlanComment[];
}

// ── Generation request ───────────────────────────────────────────────────────

export interface VisualPlanGenerateRequest {
  goal: string;
  /** Optional scoping to a single artifact. */
  sourceArtifactId?: string;
  /** Grounding context for the model (codebase search results, etc.). */
  context?: string;
}

// ── Wire messages (extension ↔ webview) ──────────────────────────────────────

export interface VisualPlanReadyMessage {
  type: 'visualPlan:ready';
  plan: VisualPlan;
}

export interface VisualPlanGeneratingMessage {
  type: 'visualPlan:generating';
  planId: string;
  goal: string;
}

export interface VisualPlanListResultMessage {
  type: 'visualPlan:list:result';
  plans: VisualPlan[];
}

export interface VisualPlanErrorMessage {
  type: 'visualPlan:error';
  error: string;
  planId?: string;
}

export interface VisualPlanApproveMessage {
  type: 'visualPlan:approve';
  planId: string;
  taskIds: string[];
}

export interface VisualPlanRequestChangesMessage {
  type: 'visualPlan:requestChanges';
  planId: string;
  comments: { sectionId: string; body: string }[];
}

export interface VisualPlanCommentMessage {
  type: 'visualPlan:comment';
  planId: string;
  comment: { sectionId: string; body: string };
}

export type VisualPlanWireMessage =
  | VisualPlanReadyMessage
  | VisualPlanGeneratingMessage
  | VisualPlanListResultMessage
  | VisualPlanErrorMessage;

// ── Hooks (injected by extension.ts) ─────────────────────────────────────────

export interface VisualPlanHooks {
  /** Generate a plan by calling the AI provider. */
  generate(request: VisualPlanGenerateRequest): Promise<VisualPlan>;
  /** Persist an approved task as a real story artifact. */
  persistTask(task: PlanTask, planId: string): Promise<string>;
  /** Notify the AutoScheduler of a newly-created ready-for-dev story. */
  notifyScheduler?(storyId: string): void;
}
