'use strict';
/**
 * scripts/prepublish-guard.js
 *
 * OS-aware guard for `vscode:prepublish`. On Linux hosts we force a
 * `rebuild:node-pty` so the linux-x64 prebuild (pty.node) is regenerated
 * against whatever Electron ABI VS Code is currently shipping; on Windows
 * / macOS the rebuild is skipped because the MSBuild / Xcode chain there
 * frequently errors on missing Spectre-mitigated libs / SDKs and the
 * shipped node-pty prebuilds already cover those host arches.
 *
 * The companion-script form (rather than inline `node -e` in
 * package.json) was chosen for readability and to keep cross-platform
 * shell-quoting out of the npm scripts section.
 */
const { execSync } = require('child_process');
const os = require('os');

const platform = os.platform();
const arch = os.arch();
console.log(`[prepublish-guard] host: ${platform}/${arch}`);

if (platform === 'linux') {
  console.log('[prepublish-guard] linux host detected -> running rebuild:node-pty so the linux-x64 prebuild matches the current VS Code Electron ABI');
  execSync('npm run rebuild:node-pty', { stdio: 'inherit' });
} else {
  console.log(`[prepublish-guard] non-linux host (${platform}) -> skipping rebuild; linux-x64 prebuild is regenerated by Linux CI`);
}
